[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
bot = { path = "../bot/" }
persistence = { path = "../persistence/" }
domain = { workspace = true }
teloxide = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true, features = ["sqlite"] }
anyhow = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
serde_json = "1"
