[package]
name = "persistence"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
sqlx = { workspace = true, features = ["sqlite"] }
chrono = { workspace = true }
domain = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
