[package]
name = "bot"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { workspace = true }
persistence = { path = "../persistence/" }
teloxide = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
